adapter.release-line=4.0
adapter.cassandra-version=4.0.17
adapter.minimum-cassandra-version=4.0.17
adapter.maximum-cassandra-version=4.0.17
adapter.minimum-java-version=8
adapter.maximum-java-version=11
adapter.runtime-class=com.axonops.sstable.worker.cassandra40.Cassandra40Runtime
