adapter.release-line=4.1
adapter.cassandra-version=4.1.3
adapter.minimum-cassandra-version=4.1.3
adapter.maximum-cassandra-version=4.1.3
adapter.minimum-java-version=11
adapter.maximum-java-version=11
adapter.runtime-class=com.axonops.sstable.worker.cassandra41.Cassandra41Runtime
