adapter.release-line=4.1
adapter.cassandra-version=4.1.11
adapter.minimum-cassandra-version=4.1.0
adapter.maximum-cassandra-version=4.1.11
adapter.minimum-java-version=11
adapter.maximum-java-version=11
adapter.import-supported=true
adapter.runtime-class=com.axonops.sstable.worker.cassandra41.Cassandra41Runtime
